# dataSource config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jamigo
    username: root
    password: as04520203
    driver-class-name: com.mysql.jdbc.Driver
    hikari.minimum-idle: 5
    hikari.maximum-pool-size: 10
    hikari.connection-timeout: 30000
  
  
  #JPA/Hibernate config
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  
  #Spring Web config
  thymeleaf:
    enabled: false
server:
  servlet:
      context-path: /login_logup_forgotpassword

  #logback config
logging:
  level:
    tw.idv.login_logup_forgotpassword: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%level] [%t] %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%level] [%t] [%line] %msg%n"
  file:
    path: "./"




